export const LOGIN = {
  LOGIN_USERNAME: 'LOGIN_USERNAME',
  LOGOUT: 'LOGOUT',
  CLEAR_DATA: 'CLEAR_DATA',
};

export const REGISTER = {
  REGISTER_USER: 'REGISTER_USER',
};

export const RESTAURENTS = {
  RESTAURENTS_LIST: 'RESTAURENTS_LIST',
};

export const COMMON_TYPES = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  FAILURE: '_FAILURE',
  RESET: '_RESET',
};

export const MAKE_API_REQUEST = 'MAKE_API_REQUEST';
